# Generated by Django 4.1.4 on 2022-12-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IRCTC.gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IRCTC.nationality'),
        ),
    ]
