# Generated by Django 4.1.4 on 2022-12-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0002_alter_user_gender_alter_user_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_choice',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
