# Generated by Django 4.1.4 on 2022-12-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0004_alter_bookings_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_choice', models.CharField(default='No Preference', max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default='Passenger Name')),
                ('age', models.CharField(default='Sge', max_length=25)),
                ('preference', models.IntegerField()),
                ('gender', models.ForeignKey(default='Gender', on_delete=django.db.models.deletion.CASCADE, to='IRCTC.gender')),
                ('nationality', models.ForeignKey(default='India', on_delete=django.db.models.deletion.CASCADE, to='IRCTC.nationality')),
            ],
        ),
    ]
