# Generated by Django 4.1.4 on 2022-12-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0005_preference_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='preference',
            field=models.ForeignKey(default='No Preference', on_delete=django.db.models.deletion.CASCADE, to='IRCTC.preference'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference_choice',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
