# Generated by Django 4.1.4 on 2022-12-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0006_alter_passengers_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender_choice',
            field=models.CharField(default='Gender', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality_choice',
            field=models.CharField(default='India', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRCTC.gender'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRCTC.nationality'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRCTC.preference'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preference_choice',
            field=models.CharField(default='No Preference', max_length=12, unique=True),
        ),
    ]
