# Generated by Django 4.1.4 on 2022-12-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0008_remove_trains_seats_ac_remove_trains_seats_sleeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='arrival',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='trains',
            name='departure',
            field=models.CharField(default='', max_length=16),
        ),
    ]
