# Generated by Django 4.1.4 on 2023-01-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0009_trains_arrival_trains_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
