# Generated by Django 4.1.4 on 2022-12-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0009_trains_arrival_trains_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='name',
            field=models.CharField(default='Passenger Name', max_length=25),
        ),
    ]
