# Generated by Django 4.1.4 on 2023-01-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0010_trains_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
