# Generated by Django 4.1.4 on 2023-01-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRCTC', '0011_alter_passengers_gender_alter_passengers_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='arrival_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
